Models/ErrorViewModel.cs
namespace KhuatDinhQuang_211200865.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/HangHoa.cs
using System;
using System.Collections.Generic;

namespace KhuatDinhQuang_211200865.Models
{
    public partial class HangHoa
    {
        public int MaHang { get; set; }
        public int MaLoai { get; set; }
        public string TenHang { get; set; } = null!;
        public decimal? Gia { get; set; }
        public string? Anh { get; set; }

        public virtual LoaiHang MaLoaiNavigation { get; set; } = null!;
    }
}

Models/LoaiHang.cs
using System;
using System.Collections.Generic;

namespace KhuatDinhQuang_211200865.Models
{
    public partial class LoaiHang
    {
        public LoaiHang()
        {
            HangHoas = new HashSet<HangHoa>();
        }

        public int MaLoai { get; set; }
        public string TenLoai { get; set; } = null!;

        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}

Models/QLHangHoaContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace KhuatDinhQuang_211200865.Models
{
    public partial class QLHangHoaContext : DbContext
    {
        public QLHangHoaContext()
        {
        }

        public QLHangHoaContext(DbContextOptions<QLHangHoaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<HangHoa> HangHoas { get; set; } = null!;
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; } = null!;
        public virtual DbSet<TblAccount> TblAccounts { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(local);Initial Catalog=QLHangHoa;User ID=sa;Password=123456");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HangHoa>(entity =>
            {
                entity.HasKey(e => e.MaHang);

                entity.ToTable("HangHoa");

                entity.Property(e => e.Anh).HasMaxLength(100);

                entity.Property(e => e.Gia).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.TenHang).HasMaxLength(50);

                entity.HasOne(d => d.MaLoaiNavigation)
                    .WithMany(p => p.HangHoas)
                    .HasForeignKey(d => d.MaLoai)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_HangHoa_LoaiHang");
            });

            modelBuilder.Entity<LoaiHang>(entity =>
            {
                entity.HasKey(e => e.MaLoai);

                entity.ToTable("LoaiHang");

                entity.Property(e => e.TenLoai).HasMaxLength(50);
            });

            modelBuilder.Entity<TblAccount>(entity =>
            {
                entity.HasKey(e => e.Uid);

                entity.ToTable("tblAccount");

                entity.Property(e => e.Password)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Username)
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Models/TblAccount.cs
using System;
using System.Collections.Generic;

namespace KhuatDinhQuang_211200865.Models
{
    public partial class TblAccount
    {
        public int Uid { get; set; }
        public string? Username { get; set; }
        public string? Password { get; set; }
    }
}

Controllers/HomeController.cs
using KhuatDinhQuang_211200865.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace KhuatDinhQuang_211200865.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly QLHangHoaContext _context;

        public HomeController(ILogger<HomeController> logger,QLHangHoaContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var hangHoas = _context.HangHoas.Where(hh=>hh.Gia>100).ToList();
            return View("KhuatDinhQuang_MainContent",hangHoas);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult HangHoaFilter(int ?hid)
        {
            var hangHoas = _context.HangHoas.Where(hh => hh.MaLoai == hid).ToList();
            return PartialView("HangHoaFilter",hangHoas);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.LoaiHangID = new SelectList(_context.LoaiHangs, "MaLoai", "TenLoai");
            return View();
        }

        [HttpPost]
        public IActionResult Create(HangHoa hanghoa)
        {
            _context.HangHoas.Add(hanghoa);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

ViewComponents/KhuatDinhQuang_HeaderViewComponent.cs
using KhuatDinhQuang_211200865.Models;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.InteropServices;

namespace KhuatDinhQuang_211200865.ViewComponents
{
	public class KhuatDinhQuang_HeaderViewComponent:ViewComponent
	{
		private readonly QLHangHoaContext _context;
		private List<LoaiHang> loaiHangs;

		public KhuatDinhQuang_HeaderViewComponent(QLHangHoaContext context)
		{
			_context = context;	
			loaiHangs=_context.LoaiHangs.ToList();
		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View("KhuatDinhQuang_Header",loaiHangs);
		}
	}
}

Views/Home/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/KhuatDinhQuang_Layout.cshtml";
}
@model HangHoa
@await Component.InvokeAsync("KhuatDinhQuang_Header")
<h2>
    <div>Khuất Đình Quang</div>
    <div>Thêm hàng hóa mới</div>
</h2>
<hr />
<div>
    <form asp-controller="Home" asp-action="Create" method="post">
        <div class="form-group">
            <label>Loại hàng</label><br />
            <select asp-items="@ViewBag.LoaiHangID" asp-for="MaLoai"></select>
        </div>
        <div class="form-group">
            <label>Tên hàng</label><br />
            <input asp-for="TenHang" class="form-control" />
        </div>

        <div class="form-group">
            <label>Giá</label><br />
            <input asp-for="Gia" class="form-control" />
        </div>

        <div class="form-group">
            <label>Ảnh</label><br />
            <input asp-for="Anh" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Views/Home/HangHoaFilter.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<HangHoa>
@foreach(HangHoa hh in Model)
{
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="~/images/@hh.Anh" alt="" /></a>
		<h2>Lorem Ipsum is simply </h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$@hh.Gia</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/KhuatDinhQuang_MainContent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/KhuatDinhQuang_Layout.cshtml";
}
@model IEnumerable<HangHoa>
@await Component.InvokeAsync("KhuatDinhQuang_Header")
<div class="main">
	<div class="content">
		<!-- Begin New Product -->
		<div class="content_top">
			<div class="heading">
				<h3>Khuất Đình Quang</h3>
			</div>
			<div class="see">
				<p><a asp-controller="Home" asp-action="Index">See all Products</a></p>
			</div>
			<div class="clear"></div>
		</div>
		<div class="section group">
			@foreach(HangHoa hh in Model)
			{
				<div class="grid_1_of_4 images_1_of_4">
					<a href="preview.html"><img src="~/images/@hh.Anh" alt="" /></a>
					<h2>Lorem Ipsum is simply </h2>
					<div class="price-details">
						<div class="price-number">
							<p><span class="rupees">$@hh.Gia</span></p>
						</div>
						<div class="add-cart">
							<h4><a href="preview.html">Add to Cart</a></h4>
						</div>
						<div class="clear"></div>
					</div>
				</div>
			}
			<!--<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/feature-pic2.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$899.75</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/feature-pic3.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$599.00</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/feature-pic4.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$679.87</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/feature-pic4.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$679.87</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>-->
		</div>
		<!-- End New Product -->
		<!-- Begin Feature Products -->
		<!--<div class="content_bottom">
			<div class="heading">
				<h3>Feature Products</h3>
			</div>
			<div class="see">
				<p><a href="#">See all Products</a></p>
			</div>
			<div class="clear"></div>
		</div>
		<div class="section group">
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/new-pic1.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$849.99</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/new-pic2.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$599.99</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/new-pic4.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$799.99</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="~/images/new-pic3.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$899.99</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>-->
		<!-- End Feature Products -->
	</div>
</div>

@section Script{
	<script>
		$('li .filter').click(function (e) {
			var hid = $(this).attr("id");
			$.ajax({
				url: "Home/HangHoaFilter",
				data: {hid},
				success: function (response) {
					$('.main .section').html(response);
				}
			})
		})
	</script>
}

Views/Shared/Components/KhuatDinhQuang_Header/KhuatDinhQuang_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<LoaiHang>
<div class="header">
	<div class="header_top">
		<div class="logo">
			<a href="index.html"><img src="~/images/logo.png" alt="" /></a>
		</div>
		<div class="cart">
			<p>
				Welcome to our Online Store! <span>Cart:</span><div id="dd" class="wrapper-dropdown-2">
					0 item(s) - $0.00
					<ul class="dropdown">
						<li>you have no items in your Shopping cart</li>
					</ul>
				</div>
			</p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="header_bottom">
		<div class="menu">
			<ul>
				<li class="active"><a asp-controller="Home" asp-action="Index">Khuất Đình Quang</a></li>
				@foreach(LoaiHang lh in Model){
					<li><a class="filter" id="@lh.MaLoai">@lh.TenLoai</a></li>
				}
				<!--<li><a >Delivery</a></li>
				<li><a >News</a></li>
				<li><a >Contact</a></li>
				<div class="clear"></div>-->
			</ul>
		</div>
		<div class="search_box">
			<form>
				<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
				<input type="button" value="">
			</form>
		</div>
		<div class="clear"></div>
	</div>
</div>

Views/Shared/KhuatDinhQuang_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="footer">
	<div class="wrap">
		<div class="section group">
			<div class="col_1_of_4 span_1_of_4">
				<h4>Information</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Advanced Search</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Why buy from us</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Privacy Policy</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>My account</h4>
				<ul>
					<li><a href="contact.html">Sign In</a></li>
					<li><a href="index.html">View Cart</a></li>
					<li><a href="#">My Wishlist</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Contact</h4>
				<ul>
					<li><span>+91-123-456789</span></li>
					<li><span>+00-123-000000</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>

Views/Shared/KhuatDinhQuang_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE HTML>
<head>
	<title>Free Home Shoppe Website Template | Home :: w3layouts</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
	<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
	<!-- Begin Wrap -->
	<div class="wrap">
		<!-- Begin Header -->
		<!-- End Header -->
		<!-- Begin Main -->
		@RenderBody()
		<!-- End Main -->
	</div>
	<!-- End Wrap -->
	<!-- Begin Footer -->
	<partial name="KhuatDinhQuang_Footer"/>
	<!-- End Footer -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@RenderSection("Script",required:false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KhuatDinhQuang_211200865</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KhuatDinhQuang_211200865.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KhuatDinhQuang_211200865</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KhuatDinhQuang_211200865 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>